# Generated from haberdasher.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt import empty_pb

if TYPE_CHECKING:
    from protobuf import DescFile


_HatFields: TypeAlias = Literal["size", "color", "name"]

class Hat(Message[_HatFields]):
    """
    A Hat is a piece of headwear made by a Haberdasher.

    ```proto
    message connectrpc.example.Hat
    ```

    Attributes:
        size:
            The size of a hat should always be in inches.

            ```proto
            int32 size = 1;
            ```
        color:
            The color of a hat will never be 'invisible', but other than
            that, anything is fair game.

            ```proto
            string color = 2;
            ```
        name:
            The name of a hat is it's type. Like, 'bowler', or something.

            ```proto
            optional string name = 3;
            ```
    """

    __slots__ = ("size", "color", "name")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            size: int = 0,
            color: str = "",
            name: str | None = None,
        ) -> None:
            pass

        size: int
        color: str
        name: str

    _PartFields: TypeAlias = Literal["id"]

    class Part(Message[_PartFields]):
        """
        A part within a Hat.

        ```proto
        message connectrpc.example.Hat.Part
        ```

        Attributes:
            id:
                The ID of the part.

                ```proto
                string id = 1;
                ```
        """

        __slots__ = ("id",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                id: str = "",
            ) -> None:
                pass

            id: str

_SizeFields: TypeAlias = Literal["inches", "description"]

class Size(Message[_SizeFields]):
    """
    Size is passed when requesting a new hat to be made. It's always
    measured in inches.

    ```proto
    message connectrpc.example.Size
    ```

    Attributes:
        inches:
            ```proto
            int32 inches = 1;
            ```
        description:
            Additional description or notes about the requested hat

            ```proto
            string description = 2;
            ```
    """

    __slots__ = ("inches", "description")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            inches: int = 0,
            description: str = "",
        ) -> None:
            pass

        inches: int
        description: str


_DESC = file_desc(
    b'\n\x11haberdasher.proto\x12\x12connectrpc.example\x1a\x1bgoogle/protobuf/empty.proto"i\n\x03Hat\x12\x12\n\x04size\x18\x01 \x01(\x05R\x04size\x12\x14\n\x05color\x18\x02 \x01(\tR\x05color\x12\x17\n\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x1a\x16\n\x04Part\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02idB\x07\n\x05_name"@\n\x04Size\x12\x16\n\x06inches\x18\x01 \x01(\x05R\x06inches\x12 \n\x0bdescription\x18\x02 \x01(\tR\x0bdescription2\xb7\x03\n\x0bHaberdasher\x12A\n\x07MakeHat\x12\x18.connectrpc.example.Size\x1a\x17.connectrpc.example.Hat"\x03\x90\x02\x01\x12H\n\x0fMakeFlexibleHat\x12\x18.connectrpc.example.Size\x1a\x17.connectrpc.example.Hat"\x00(\x01\x12K\n\x0fMakeSimilarHats\x12\x18.connectrpc.example.Size\x1a\x17.connectrpc.example.Hat"\x03\x90\x02\x010\x01\x12J\n\x0fMakeVariousHats\x12\x18.connectrpc.example.Size\x1a\x17.connectrpc.example.Hat"\x00(\x010\x01\x12E\n\tListParts\x12\x16.google.protobuf.Empty\x1a\x1c.connectrpc.example.Hat.Part"\x000\x01\x12;\n\tDoNothing\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\tZ\x07exampleb\x06proto3',
    [
        empty_pb.desc(),
    ],
    {
        "Hat": Hat,
        "Hat.Part": Hat.Part,
        "Size": Size,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `haberdasher.proto`."""
    return _DESC
