version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: uv
    directories:
      - "**/*"
    schedule:
      interval: weekly
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directories:
      - "protoc-gen-connect-python/"
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
