site_name: Connect Documentation

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            members_order: source
            merge_init_into_class: true
            show_signature: false
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://googleapis.dev/python/protobuf/latest/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      default_lang: python
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
