# Generated from haberdasher.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from google.protobuf.empty_pb2 import Empty
from pyqwest import Client, SyncClient

from .haberdasher_pb2 import Hat, Size

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class Haberdasher(Protocol):
    async def make_hat(self, request: Size, ctx: RequestContext[Size, Hat]) -> Hat:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def make_flexible_hat(self, request: AsyncIterator[Size], ctx: RequestContext[Size, Hat]) -> Hat:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def make_similar_hats(self, request: Size, ctx: RequestContext[Size, Hat]) -> AsyncIterator[Hat]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def make_various_hats(self, request: AsyncIterator[Size], ctx: RequestContext[Size, Hat]) -> AsyncIterator[Hat]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_parts(self, request: Empty, ctx: RequestContext[Empty, Hat.Part]) -> AsyncIterator[Hat.Part]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def do_nothing(self, request: Empty, ctx: RequestContext[Empty, Empty]) -> Empty:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class HaberdasherASGIApplication(ConnectASGIApplication[Haberdasher]):
    def __init__(
        self,
        service: Haberdasher | AsyncGenerator[Haberdasher],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/connectrpc.example.Haberdasher/MakeHat": Endpoint.unary(
                    method=MethodInfo(
                        name="MakeHat",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.make_hat,
                ),
                "/connectrpc.example.Haberdasher/MakeFlexibleHat": Endpoint.client_stream(
                    method=MethodInfo(
                        name="MakeFlexibleHat",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.make_flexible_hat,
                ),
                "/connectrpc.example.Haberdasher/MakeSimilarHats": Endpoint.server_stream(
                    method=MethodInfo(
                        name="MakeSimilarHats",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.make_similar_hats,
                ),
                "/connectrpc.example.Haberdasher/MakeVariousHats": Endpoint.bidi_stream(
                    method=MethodInfo(
                        name="MakeVariousHats",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.make_various_hats,
                ),
                "/connectrpc.example.Haberdasher/ListParts": Endpoint.server_stream(
                    method=MethodInfo(
                        name="ListParts",
                        service_name="connectrpc.example.Haberdasher",
                        input=Empty,
                        output=Hat.Part,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_parts,
                ),
                "/connectrpc.example.Haberdasher/DoNothing": Endpoint.unary(
                    method=MethodInfo(
                        name="DoNothing",
                        service_name="connectrpc.example.Haberdasher",
                        input=Empty,
                        output=Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.do_nothing,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/connectrpc.example.Haberdasher"


class HaberdasherClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def make_hat(
        self,
        request: Size,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> Hat:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MakeHat",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def make_flexible_hat(
        self,
        request: AsyncIterator[Size],
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Hat:
        return await self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="MakeFlexibleHat",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def make_similar_hats(
        self,
        request: Size,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[Hat]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="MakeSimilarHats",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def make_various_hats(
        self,
        request: AsyncIterator[Size],
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[Hat]:
        return self.execute_bidi_stream(
            request=request,
            method=MethodInfo(
                name="MakeVariousHats",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_parts(
        self,
        request: Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[Hat.Part]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="ListParts",
                service_name="connectrpc.example.Haberdasher",
                input=Empty,
                output=Hat.Part,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def do_nothing(
        self,
        request: Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DoNothing",
                service_name="connectrpc.example.Haberdasher",
                input=Empty,
                output=Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class HaberdasherSync(Protocol):
    def make_hat(self, request: Size, ctx: RequestContext[Size, Hat]) -> Hat:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def make_flexible_hat(self, request: Iterator[Size], ctx: RequestContext[Size, Hat]) -> Hat:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def make_similar_hats(self, request: Size, ctx: RequestContext[Size, Hat]) -> Iterator[Hat]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def make_various_hats(self, request: Iterator[Size], ctx: RequestContext[Size, Hat]) -> Iterator[Hat]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_parts(self, request: Empty, ctx: RequestContext[Empty, Hat.Part]) -> Iterator[Hat.Part]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def do_nothing(self, request: Empty, ctx: RequestContext[Empty, Empty]) -> Empty:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class HaberdasherWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: HaberdasherSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/connectrpc.example.Haberdasher/MakeHat": EndpointSync.unary(
                    method=MethodInfo(
                        name="MakeHat",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.make_hat,
                ),
                "/connectrpc.example.Haberdasher/MakeFlexibleHat": EndpointSync.client_stream(
                    method=MethodInfo(
                        name="MakeFlexibleHat",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.make_flexible_hat,
                ),
                "/connectrpc.example.Haberdasher/MakeSimilarHats": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="MakeSimilarHats",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.make_similar_hats,
                ),
                "/connectrpc.example.Haberdasher/MakeVariousHats": EndpointSync.bidi_stream(
                    method=MethodInfo(
                        name="MakeVariousHats",
                        service_name="connectrpc.example.Haberdasher",
                        input=Size,
                        output=Hat,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.make_various_hats,
                ),
                "/connectrpc.example.Haberdasher/ListParts": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="ListParts",
                        service_name="connectrpc.example.Haberdasher",
                        input=Empty,
                        output=Hat.Part,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_parts,
                ),
                "/connectrpc.example.Haberdasher/DoNothing": EndpointSync.unary(
                    method=MethodInfo(
                        name="DoNothing",
                        service_name="connectrpc.example.Haberdasher",
                        input=Empty,
                        output=Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.do_nothing,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/connectrpc.example.Haberdasher"


class HaberdasherClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def make_hat(
        self,
        request: Size,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> Hat:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MakeHat",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def make_flexible_hat(
        self,
        request: Iterator[Size],
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Hat:
        return self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="MakeFlexibleHat",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def make_similar_hats(
        self,
        request: Size,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Iterator[Hat]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="MakeSimilarHats",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def make_various_hats(
        self,
        request: Iterator[Size],
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Iterator[Hat]:
        return self.execute_bidi_stream(
            request=request,
            method=MethodInfo(
                name="MakeVariousHats",
                service_name="connectrpc.example.Haberdasher",
                input=Size,
                output=Hat,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_parts(
        self,
        request: Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Iterator[Hat.Part]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="ListParts",
                service_name="connectrpc.example.Haberdasher",
                input=Empty,
                output=Hat.Part,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def do_nothing(
        self,
        request: Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DoNothing",
                service_name="connectrpc.example.Haberdasher",
                input=Empty,
                output=Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
