# Generated from status.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt import any_pb

if TYPE_CHECKING:
    from protobuf import DescFile
    from protobuf.wkt import Any


_StatusFields: TypeAlias = Literal["code", "message", "details"]

class Status(Message[_StatusFields]):
    """
    See https://cloud.google.com/apis/design/errors.

    This struct must remain binary-compatible with
    https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto.

    ```proto
    message grpc.status.v1.Status
    ```

    Attributes:
        code:
            a google.rpc.Code

            ```proto
            int32 code = 1;
            ```
        message:
            developer-facing, English (localize in details or client-side)

            ```proto
            string message = 2;
            ```
        details:
            ```proto
            repeated google.protobuf.Any details = 3;
            ```
    """

    __slots__ = ("code", "message", "details")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            code: int = 0,
            message: str = "",
            details: list[Any] | None = None,
        ) -> None:
            pass

        code: int
        message: str
        details: list[Any]


_DESC = file_desc(
    b'\n\x0cstatus.proto\x12\x0egrpc.status.v1\x1a\x19google/protobuf/any.proto"f\n\x06Status\x12\x12\n\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12.\n\x07details\x18\x03 \x03(\x0b2\x14.google.protobuf.AnyR\x07detailsb\x06proto3',
    [
        any_pb.desc(),
    ],
    {
        "Status": Status,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `status.proto`."""
    return _DESC
