name: Add issues and PRs to project

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
  pull_request_target:
    types:
      - opened
      - reopened
  issue_comment:
    types:
      - created

# GitHub token created from secret so default token not used.
permissions: {}

jobs:
  call-workflow-add-to-project:
    name: Call workflow to add issue to project
    uses: connectrpc/base-workflows/.github/workflows/add-to-project.yaml@2c9b8323e8bc69bf296e283f13fcae22f3aa6a60 # main
    secrets: inherit
