name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        resolution: ["highest", "lowest-direct"]
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
        python:
          - "3.10"
          - "3.14"
        coverage:
          - "nocov"
        # Test oldest and newest on all OS's, but others only on one
        # to save CI load.
        include:
          - os: ubuntu-24.04
            python: "3.11"
            coverage: "nocov"
            resolution: "lowest-direct"
          - os: ubuntu-24.04
            python: "3.12"
            coverage: "nocov"
            resolution: "lowest-direct"
          - os: ubuntu-24.04
            python: "3.13"
            coverage: "nocov"
            resolution: "lowest-direct"
          # Enable coverage on just one job
          - os: ubuntu-24.04
            python: "3.14"
            coverage: "cov"
            resolution: "lowest-direct"
    env:
      # Shared env variables for all the tests
      UV_RESOLUTION: "${{ matrix.resolution }}"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: protoc-gen-connect-python/go.mod
          cache-dependency-path: "**/go.mod"

      - run: uv sync --frozen

      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: uv run poe lint

      - name: run python tests
        run: uv run poe test ${{ matrix.coverage == 'cov' && '--cov=connectrpc --cov-report=xml' || '' }}

      - name: run conformance tests
        # TODO: Debug stdin/stdout issues on Windows
        if: ${{ !startsWith(matrix.os, 'windows-') }}
        run: uv run poe test-conformance ${{ matrix.coverage == 'cov' && '--cov=connectrpc --cov-report=xml' || '' }}

      - name: run OTel tests
        run: uv run poe test-otel ${{ matrix.coverage == 'cov' && '--cov=connectrpc_otel --cov-report=xml' || '' }}

      - name: run Go tests
        run: go test ./...
        working-directory: protoc-gen-connect-python

      - name: check running generate does not create a diff
        # NOTE: running on macOS as our sed command only works there
        # We expect uv.lock to change when matrix.resolution == "lowest-direct", so we don't check it there.
        if: ${{ startsWith(matrix.os, 'macos-') && matrix.resolution == 'highest' }}
        run: uv run poe checkgenerate
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}

      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        if: ${{ matrix.coverage == 'cov' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - run: uv sync --frozen

      - run: uv build

      # Builds to root dist directory so published together with the main project.
      - run: uv build
        working-directory: connectrpc-otel

      - name: build codegen archives
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: "~> v2"
          args: release --snapshot --clean
          workdir: protoc-gen-connect-python

      - run: |
          uv sync --frozen
          uv run python scripts/generate_wheels.py
        working-directory: protoc-gen-connect-python

      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        if: github.event_name != 'pull_request'
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: publish protoc-gen-connect-python
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        if: github.event_name != 'pull_request'
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: protoc-gen-connect-python/dist
          skip-existing: true
