name: Release connectrpc-otel
on:
  push:
    tags:
      - "connectrpc-otel/v*"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    environment: pypi-release
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - run: uv sync --frozen

      # Builds into root dist directory
      - run: uv build
        working-directory: connectrpc-otel

      - name: publish connectrpc-otel
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          skip-existing: true
